---
# Source: helm for kubernetes/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bunathpheng-4e92e7f3                  # Ingress name
  labels:
    app: bunathpheng-4e92e7f3
spec:
  ingressClassName: nginx   # Optional ingressClass
  rules:
    - host: "bunathpheng-4e92e7f3.smartops.space"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bunathpheng-4e92e7f3               # Links to Service name dynamically
                port:
                  number: 8080  # Links to service port dynamically
